### ISSUE TITLE
responsive design

### ISSUE THREAD

**Issue by hakuturu583** [tier4/ros-metrics-reporter#5]
Great work!
I see your github pages from Iphone.
And I fonud this page is not responsive design.
![1E58A118-7DA5-4654-B531-58F569FE2FA2](https://user-images.githubusercontent.com/10348912/118829127-d3d0aa80-b8f8-11eb-8e89-9ce76f5e227c.png)

**Comment by KeisukeShima** [comment]
Thanks for reporting! This problem seems to occur only in the table tag.
I will start investigating for a solution.

related:
https://discourse.gohugo.io/t/responsive-tables-in-markdown/10639/11

**Comment by KeisukeShima** [comment]
@hakuturu583 Starting with `v0.2.0`, this feature is supported :rocket:
